### PR TITLE
feat: add save input and expected

### LINKED ISSUE #25: Save the inputs and outputs in the file
**Is your feature request related to a problem? Please describe.**

I need to re-enter the inputs and outputs when I open a file again.

**Describe the solution you'd like**

Save the corresponding relationship between the file path and the inputs and outputs in CP Editor, when opening files with the same path, the inputs and outputs are the same.

**Describe alternatives you've considered**

Save the inputs and outputs in the file, for example, save them in the annotations with JSON.

**Additional context**

It's from [this comment](https://codeforces.com/blog/entry/71907?#comment-562683) .

### PR DESCRIPTION
**Pull request by ouuan**
This closes #25.

It hasn't been well tested yet. Maybe I'll check it again tomorrow.

Now, only input1/expected1 has been implemented, 2 and 3 can be added after making sure that 1 works well. (Maybe it's time to kill the 1/2/3 parts.)

### CODE REVIEW

**Comment by coder3101** [comment]
Nice work, Seems good! Do as you want to get rid of those 1/2/3 stuff, i am currently working on setting automation so that i don't have to manually build and release stuffs, it all could be done with just a `git push`. Soon master will freeze. After next release hits, and all development and PR should be done on development branch, and this branch code will release a new beta update for each commit! Master will release stable updates.

**Comment by ouuan** [comment]
A question: why do you use kill for compile and run but terminate for run?

**Comment by coder3101** [comment]
> A question: why do you use kill for compile and run but terminate for run?

No particular reason, but because SIGMTERM is less severe than SIGKILL. But it doesn't matter much

**Comment by ouuan** [comment]
It seems that `OutputWriter` is never used, is it there for future usage?

**Comment by coder3101** [comment]
No, it was originally mean to store Expected outputs, but it won't be used as now it's in those QString pointers.

**Comment by coder3101** [comment]
When your work is done here. Let me know, I am releasing `3.1.0` today. This work will be released in next week;s release.

**Comment by ouuan** [comment]
My todo list for this PR is empty now. I've been using this version for one day and didn't find any issues. Bugs can be fixed later if they are found.

**Comment by coder3101** [comment]
Now, new releases are published by Azure Pipelines. It uses commit messages to generate the change-log for every new release. Please make sure to detail the commit messages.

**Comment by ouuan** [comment]
Commit messages have been rewritten with a force-push.

**Comment by ouuan** [comment]
Do you want to merge it and make a new release?

**Comment by coder3101** [comment]
Yeah sure! I see it's only code cleanup and refactoring. If there is any changelogs. Please comment it, I will merge and release a new version as soon as you provide me a changelog.

**Comment by ouuan** [comment]
I think the [new commit message](https://github.com/coder3101/cp-editor2/pull/52/commits/6e0d024bedcb1a1d9008db1843d4758118a8db1c) is clear enough.

**Comment by coder3101** [comment]
That's nice! I will merge it now and once i test them locally. In a few minutes, I will release it!

**Pull request merged**
