### PR TITLE
feat(mainwindow): add verdict colors

### LINKED ISSUE #28: Show verdicts with color
**Is your feature request related to a problem? Please describe.**

The verdicts are not conspicuous since the font is small and both AC and WA are white.

**Describe the solution you'd like**

Use green for AC and red for WA.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by ouuan**
fixes #28 

(It seems that I lied in https://github.com/coder3101/cp-editor2/issues/14#issuecomment-565227522 . In fact, I haven't learnt Python/JavaScript/PHP before using them, either. I just Google for it when I need to implement something. Same for this PR.)

### CODE REVIEW

**Comment by ouuan** [comment]
Oh, I've only tested it in the dark them.

**Comment by coder3101** [comment]
So DOES it looks visible the Verdict color on both the themes?

**Comment by coder3101** [comment]
Once you confirm that there is contrast between verdict colour on both themes, i will approve changes, if there isn't you could change colours slightly to make it look better in both themes.

**Comment by ouuan** [comment]
image

image

What do you think?

**Comment by coder3101** [comment]
Thanks for your contribution

**Pull request merged**
