### PR TITLE
chore: add download link for Chinese users

### PR DESCRIPTION
**Pull request by ouuan**
Downloading on Github can be extremely slow (below 10KiB/s) in Mainland China, this link may be useful for them.

### CODE REVIEW

**Comment by coder3101** [comment]
So is it a mirror?

**Comment by ouuan** [comment]
No, it's uploaded by myself.

**Comment by coder3101** [comment]
So, every time a new release comes! This url will change? You must gaurantee that the binary in the above url will be latest always!

**Comment by ouuan** [comment]
The URL won't change (it will be still the same after changing the content), but manually upload is required.

**Comment by coder3101** [comment]
Okay, then you will have to upload the binaries from releases page as soon as a stable release hits. Should I merge?

**Comment by ouuan** [comment]
I'll try to upload it ASAP, or you can register on that website and upload by yourself. What do you think?

**Comment by coder3101** [comment]
I am setting Automation tools to do that for me. Anyways! Here is what you can do, keep that link and let user know that the exe downloaded from that place may not be updated. It will be easy for someone, to quickly try it after downloading then if they like they can get the latest version by visiting the release page.

**Pull request merged**
