### PR TITLE
format codes & fix format shortcut & update QCodeEditor

### PR DESCRIPTION
**Pull request by ouuan**

### CODE REVIEW

**Comment by coder3101** [comment]
I assume this code format is done by `.clangformat` in source root?

**Comment by ouuan** [comment]
> I assume this code format is done by `.clangformat` in source root?

I think so. Visual Studio said it used `.clangformat` in source root automatically.

**Comment by ouuan** [comment]
Maybe the QCodeEditor should be separated? I added it together with formatting carelessly.

**Comment by ouuan** [comment]
But I have to go to the dormitory now :(

**Comment by coder3101** [comment]
You don't need to change QCodeEditor files in PR. Instead you should update it locally with git submodule update command. I will not merge it now, you need to remove that QCodeEditor file from this PR rest is Okay. Take your time, soon i will publish the new blog about this editor. Meanwhile you could try it and so this is why it's in beta.

**Comment by ouuan** [comment]
BTW, what's the problem with the system-wide dark theme? (I don't know where to ask this question, so ask here.)

**Comment by coder3101** [comment]
> BTW, what's the problem with the system-wide dark theme? (I don't know where to ask this question, so ask here.)

Qt does not support Dark theme, the current theme is nothing but a Qt implementation of KDE that has dark theme. In KDE Plasma and other distro that mix well with Qt, you can turn on system theme Dark and it manages and changes the theme to dark. I will however look into if there is a way out.

**Comment by coder3101** [comment]
Hey, if you get some time could you also re-write(modify) the README to match the new Editor features?

**Comment by ouuan** [comment]
> > BTW, what's the problem with the system-wide dark theme? (I don't know where to ask this question, so ask here.)
> 
> Qt does not support Dark theme, the current theme is nothing but a Qt implementation of KDE that has dark theme. In KDE Plasma and other distro that mix well with Qt, you can turn on system theme Dark and it manages and changes the theme to dark. I will however look into if there is a way out.

I mean, what are the "serious UI/UX issues", and why was it available in old versions but not in the current version.

**Pull request merged**
