### PR TITLE
fix(mainwindow): use simplified instead of trimmed in diff

### LINKED ISSUE #38: Use testlib.h to check the verdicts
**Is your feature request related to a problem? Please describe.**

Now the diff viewer works incorrectly for me, I guess it's about the newline character (I'm using Windows 10, and this happens only when there are more than one lines). And I have to follow a certain format strictly, even the space characters.

**Describe the solution you'd like**

Use testlib.h to check the verdicts. Users can choose one of [the default checkers](https://github.com/MikeMirzayanov/testlib/tree/master/checkers) by a drop-down box, and [wcmp](https://github.com/MikeMirzayanov/testlib/blob/master/checkers/wcmp.cpp) is the default one.

The details besides AC/WA can be shown in the "Compiler Messages and stderr" section.

**Describe alternatives you've considered**

Use something like `diff -b` to ignore spaces.

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by ouuan**
This partially fixes #38.

### CODE REVIEW

**Comment by coder3101** [comment]
https://doc.qt.io/qt-5/qstring.html#simplified

According to docs this function replaces `\n` characters. So it basically makes everything one line, every multiline output is converted into one line output. So now following are same :

```
2
4 
6
```

and 

```
2 4 5

```

While this is obviously Wrong answer on Codeforces or any other platforms.

*Reverted the commit, Please open a new PR fixing this issue* (We need to manually implement that function I talked about in #38)

**Comment by ouuan** [comment]
> answer

In other OJs this may be WA, but in most problems on CF, white spaces don't matter.

**Comment by ouuan** [comment]
[image](https://docs.google.com/document/d/e/2PACX-1vRhazTXxSdj7JEIC7dp-nOWcUFiY8bXi9lLju-k6vVMKf4IiBmweJoOAMI-ZEZxatXF08I9wMOQpMqC/pub)

**Comment by coder3101** [comment]
Yes, So people who use Codechef and other platforms will complain about it. It will be better if newlines are maintained.

**Comment by ouuan** [comment]
Where should I write a function for comparing? It doesn't seem like a "member function".

**Comment by coder3101** [comment]
Create a function with following signature in mainwindow.cc.
```cpp
bool MainWindow::isVerdictPass(QString output, QString expected){...};
```

It should return true if verdict is `AC` otherwise false.
Create this after the definition of function `launchSession()`. 

Then you need to declare it as well, in mainwindow.hpp, just after launchSession(); declare it (private);

```cpp
....
bool isVerdictPass (QString, QString);
...
```

Then replace that `isSame` with the value returned from this call, pass the arguments as expected.

**Comment by coder3101** [comment]
> Where should I write a function for comparing? It doesn't seem like a "member function".
> 
> (In fact, almost all functions returns void.)

Yes they are member function that behave like callbacks, callbacks usually have void return type. They are normal C++ classes and functions.  No magic, you can do whatever you like.

**Pull request merged**
