### PR TITLE
feat(mainwindow): update saving logic & detect text change

### PR DESCRIPTION
**Pull request by ouuan**
This fixes the second part of #23.

It's a big change, I'm not so sure that there aren't any mistakes. Please check it carefully.

BTW, the code reuse is terrible. There are too many copy pastings, especially the 3 inputs, 3 outputs, 3 runners part.

### CODE REVIEW

**Comment by coder3101** [comment]
Yes lot of code was inherited from my old editor. Which was for personal and fun use! I will tr making it more organised !!

**Comment by ouuan** [comment]
Something should be changed in favor of `launchCompanionSession`.

**Comment by coder3101** [comment]
> Something should be changed in favor of `launchCompanionSession`.

What?

**Comment by ouuan** [comment]
> > Something should be changed in favor of `launchCompanionSession`.
> 
> What?

I would fix it. Left a comment here for:
1. self reminding;
2. don't merge.

**Comment by coder3101** [comment]
When your work is done, mention me to merge this work!

**Comment by coder3101** [comment]
Application terminates because it thinks that no window is visible. 

Read this problem and in the problem itself is the answer. 

Basically what you have to do is call `app.setQuitOnLastWindowClosed(false)` in main as soon as app is created. 

Read this answer https://stackoverflow.com/questions/5116459/problem-with-hidden-qmainwindow-application-crashes-after-qmessagebox-is-displa

**Comment by ouuan** [comment]
> Application terminates because it thinks that no window is visible.
> 
> Read this problem and in the problem itself is the answer.
> 
> Basically what you have to do is call `app.setQuitOnLastWindowClosed(false)` in main as soon as app is created.
> 
> Read this answer https://stackoverflow.com/questions/5116459/problem-with-hidden-qmainwindow-application-crashes-after-qmessagebox-is-displa

The bug still happens:

```cpp
int main(int argc, char* argv[]) {
  QApplication a(argc, argv);
  a.setQuitOnLastWindowClosed(false);
  QStringList args = a.arguments();
  QString filePath = args.size() > 1 ? args[1]: "";
  MainWindow w(filePath);
  w.show();
  return a.exec();
}
```

**Comment by ouuan** [comment]
How about this: open a new session when it's an unchanged temporary buffer (i.e. unsaved, the content is exactly the template), otherwise don't open a new session.

**Comment by ouuan** [comment]
@coder3101 

It looks good to me now, you can merge it after checking again.

**Comment by coder3101** [comment]
After i merge it today, i will release a pre-release version, `can you guarantee that New session won't crash application?`

**Comment by ouuan** [comment]
> After i merge it today, i will release a pre-release version, `can you guarantee that New session won't crash application?`

It didn't crash when I tested it, and in this version, there is no message box opened in the backstage.

**Pull request merged**
